// Code generated by "stringer -type=Code"; DO NOT EDIT.

package error

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SigningMethodError-1000]
	_ = x[EncodingError-1001]
	_ = x[DecodingError-1002]
	_ = x[ParsingJWTError-1003]
	_ = x[UserMatchError-1004]
	_ = x[InvalidTokenError-1005]
}

const _Code_name = "SigningMethodErrorEncodingErrorDecodingErrorParsingJWTErrorUserMatchErrorInvalidTokenError"

var _Code_index = [...]uint8{0, 18, 31, 44, 59, 73, 90}

func (i Code) String() string {
	i -= 1000
	if i < 0 || i >= Code(len(_Code_index)-1) {
		return "Code(" + strconv.FormatInt(int64(i+1000), 10) + ")"
	}
	return _Code_name[_Code_index[i]:_Code_index[i+1]]
}
